# Load Covid19 Data from API (https://api.covidtracking.com) into PostgreSQL Database

In [26]:
# download necessary libraries 
# requests - to process json responses
# pandas - to convert json responses into dataframe
# sqlalchemy - to establish the connection in postgresql and create the table load

In [1]:
import requests
import pandas
import sqlalchemy

In [27]:
# pass on the api url that contains data in json format
url = 'https://api.covidtracking.com/v2/states/ca/daily/simple.json'
response = requests.get(url)
# printing the response status code
# status code 200 - 
print(response.status_code)

200

In [28]:
# printing the data as in json format
responseData = response.json()
print(responseData)

{'meta': {'build_time': '2021-06-01T07:04:25.950Z', 'license': 'CC-BY-4.0', 'version': '2.0-beta'}, 'data': [{'date': '2021-03-07', 'state': 'CA', 'meta': {'data_quality_grade': 'B', 'updated': '2021-03-07T07:59:00Z', 'tests': {'total_source': 'totalTestsViral'}}, 'cases': {'total': 3501394, 'confirmed': 3501394, 'probable': None}, 'tests': {'pcr': {'total': 49646014, 'pending': None, 'encounters': {'total': None}, 'specimens': {'total': 49646014, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': 3501394, 'negative': None}}, 'antibody': {'encounters': {'total': None, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': None, 'negative': None}}, 'antigen': {'encounters': {'total': None, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': None, 'negative': None}}}, 'outcomes': {'recovered': None, 'hospitalized': {'total': None, 'currently': 4291, 'in_icu': {'total': None, 'currently': 1159}, 'on_ventilator': {'total': None, 'currently': None}}, 'death': {'total': 54124, 'confirmed': None, 'probable': None}}}, {'date': '2021-03-06', 'state': 'CA', 'meta': {'data_quality_grade': 'B', 'updated': '2021-03-06T07:59:00Z', 'tests': {'total_source': 'totalTestsViral'}}, 'cases': {'total': 3497578, 'confirmed': 3497578, 'probable': None}, 'tests': {'pcr': {'total': 49512828, 'pending': None, 'encounters': {'total': None}, 'specimens': {'total': 49512828, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': 3497578, 'negative': None}}, 'antibody': {'encounters': {'total': None, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': None, 'negative': None}}, 'antigen': {'encounters': {'total': None, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': None, 'negative': None}}}, 'outcomes': {'recovered': None, 'hospitalized': {'total': None, 'currently': 4513, 'in_icu': {'total': None, 'currently': 1221}, 'on_ventilator': {'total': None, 'currently': None}}, 'death': {'total': 53866, 'confirmed': None, 'probable': None}}}, {'date': '2021-03-05', 'state': 'CA', 'meta': {'data_quality_grade': 'B', 'updated': '2021-03-05T07:59:00Z', 'tests': {'total_source': 'totalTestsViral'}}, 'cases': {'total': 3493126, 'confirmed': 3493126, 'probable': None}, 'tests': {'pcr': {'total': 49294503, 'pending': None, 'encounters': {'total': None}, 'specimens': {'total': 49294503, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': 3493126, 'negative': None}}, 'antibody': {'encounters': {'total': None, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': None, 'negative': None}}, 'antigen': {'encounters': {'total': None, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': None, 'negative': None}}}, 'outcomes': {'recovered': None, 'hospitalized': {'total': None, 'currently': 4714, 'in_icu': {'total': None, 'currently': 1236}, 'on_ventilator': {'total': None, 'currently': None}}, 'death': {'total': 53448, 'confirmed': None, 'probable': None}}}, {'date': '2021-03-04', 'state': 'CA', 'meta': {'data_quality_grade': 'B', 'updated': '2021-03-04T07:59:00Z', 'tests': {'total_source': 'totalTestsViral'}}, 'cases': {'total': 3488467, 'confirmed': 3488467, 'probable': None}, 'tests': {'pcr': {'total': 49147685, 'pending': None, 'encounters': {'total': None}, 'specimens': {'total': 49147685, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': 3488467, 'negative': None}}, 'antibody': {'encounters': {'total': None, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': None, 'negative': None}}, 'antigen': {'encounters': {'total': None, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': None, 'negative': None}}}, 'outcomes': {'recovered': None, 'hospitalized': {'total': None, 'currently': 4967, 'in_icu': {'total': None, 'currently': 1327}, 'on_ventilator': {'total': None, 'currently': None}}, 'death': {'total': 53048, 'confirmed': None, 'probable': None}}}, {'date': '2021-03-03', 'state': 'CA', 'meta': {'data_quality_grade': 'B', 'updated': '2021-03-03T07:59:00Z', 'tests': {'total_source': 'totalTestsViral'}}, 'cases': {'total': 3484963, 'confirmed': 3484963, 'probable': None}, 'tests': {'pcr': {'total': 49028048, 'pending': None, 'encounters': {'total': None}, 'specimens': {'total': 49028048, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': 3484963, 'negative': None}}, 'antibody': {'encounters': {'total': None, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': None, 'negative': None}}, 'antigen': {'encounters': {'total': None, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': None, 'negative': None}}}, 'outcomes': {'recovered': None, 'hospitalized': {'total': None, 'currently': 5110, 'in_icu': {'total': None, 'currently': 1403}, 'on_ventilator': {'total': None, 'currently': None}}, 'death': {'total': 52775, 'confirmed': None, 'probable': None}}}, {'date': '2021-03-02', 'state': 'CA', 'meta': {'data_quality_grade': 'B', 'updated': '2021-03-02T07:59:00Z', 'tests': {'total_source': 'totalTestsViral'}}, 'cases': {'total': 3481611, 'confirmed': 3481611, 'probable': None}, 'tests': {'pcr': {'total': 48897190, 'pending': None, 'encounters': {'total': None}, 'specimens': {'total': 48897190, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': 3481611, 'negative': None}}, 'antibody': {'encounters': {'total': None, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': None, 'negative': None}}, 'antigen': {'encounters': {'total': None, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': None, 'negative': None}}}, 'outcomes': {'recovered': None, 'hospitalized': {'total': None, 'currently': 5302, 'in_icu': {'total': None, 'currently': 1452}, 'on_ventilator': {'total': None, 'currently': None}}, 'death': {'total': 52497, 'confirmed': None, 'probable': None}}}, {'date': '2021-03-01', 'state': 'CA', 'meta': {'data_quality_grade': 'B', 'updated': '2021-03-01T07:59:00Z', 'tests': {'total_source': 'totalTestsViral'}}, 'cases': {'total': 3479078, 'confirmed': 3479078, 'probable': None}, 'tests': {'pcr': {'total': 48712676, 'pending': None, 'encounters': {'total': None}, 'specimens': {'total': 48712676, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': 3479078, 'negative': None}}, 'antibody': {'encounters': {'total': None, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': None, 'negative': None}}, 'antigen': {'encounters': {'total': None, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': None, 'negative': None}}}, 'outcomes': {'recovered': None, 'hospitalized': {'total': None, 'currently': 5409, 'in_icu': {'total': None, 'currently': 1518}, 'on_ventilator': {'total': None, 'currently': None}}, 'death': {'total': 52194, 'confirmed': None, 'probable': None}}}, {'date': '2021-02-28', 'state': 'CA', 'meta': {'data_quality_grade': 'B', 'updated': '2021-02-28T07:59:00Z', 'tests': {'total_source': 'totalTestsViral'}}, 'cases': {'total': 3475562, 'confirmed': 3475562, 'probable': None}, 'tests': {'pcr': {'total': 48469106, 'pending': None, 'encounters': {'total': None}, 'specimens': {'total': 48469106, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': 3475562, 'negative': None}}, 'antibody': {'encounters': {'total': None, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': None, 'negative': None}}, 'antigen': {'encounters': {'total': None, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': None, 'negative': None}}}, 'outcomes': {'recovered': None, 'hospitalized': {'total': None, 'currently': 5674, 'in_icu': {'total': None, 'currently': 1585}, 'on_ventilator': {'total': None, 'currently': None}}, 'death': {'total': 51979, 'confirmed': None, 'probable': None}}}, {'date': '2021-02-27', 'state': 'CA', 'meta': {'data_quality_grade': 'B', 'updated': '2021-02-27T07:59:00Z', 'tests': {'total_source': 'totalTestsViral'}}, 'cases': {'total': 3470877, 'confirmed': 3470877, 'probable': None}, 'tests': {'pcr': {'total': 48219490, 'pending': None, 'encounters': {'total': None}, 'specimens': {'total': 48219490, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': 3470877, 'negative': None}}, 'antibody': {'encounters': {'total': None, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': None, 'negative': None}}, 'antigen': {'encounters': {'total': None, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': None, 'negative': None}}}, 'outcomes': {'recovered': None, 'hospitalized': {'total': None, 'currently': 5897, 'in_icu': {'total': None, 'currently': 1651}, 'on_ventilator': {'total': None, 'currently': None}}, 'death': {'total': 51821, 'confirmed': None, 'probable': None}}}, {'date': '2021-02-26', 'state': 'CA', 'meta': {'data_quality_grade': 'B', 'updated': '2021-02-26T07:59:00Z', 'tests': {'total_source': 'totalTestsViral'}}, 'cases': {'total': 3465726, 'confirmed': 3465726, 'probable': None}, 'tests': {'pcr': {'total': 47995576, 'pending': None, 'encounters': {'total': None}, 'specimens': {'total': 47995576, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': 3465726, 'negative': None}}, 'antibody': {'encounters': {'total': None, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': None, 'negative': None}}, 'antigen': {'encounters': {'total': None, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': None, 'negative': None}}}, 'outcomes': {'recovered': None, 'hospitalized': {'total': None, 'currently': 6152, 'in_icu': {'total': None, 'currently': 1725}, 'on_ventilator': {'total': None, 'currently': None}}, 'death': {'total': 51382, 'confirmed': None, 'probable': None}}}, {'date': '2021-02-25', 'state': 'CA', 'meta': {'data_quality_grade': 'B', 'updated': '2021-02-25T07:59:00Z', 'tests': {'total_source': 'totalTestsViral'}}, 'cases': {'total': 3460326, 'confirmed': 3460326, 'probable': None}, 'tests': {'pcr': {'total': 47814160, 'pending': None, 'encounters': {'total': None}, 'specimens': {'total': 47814160, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': 3460326, 'negative': None}}, 'antibody': {'encounters': {'total': None, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': None, 'negative': None}}, 'antigen': {'encounters': {'total': None, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': None, 'negative': None}}}, 'outcomes': {'recovered': None, 'hospitalized': {'total': None, 'currently': 6520, 'in_icu': {'total': None, 'currently': 1783}, 'on_ventilator': {'total': None, 'currently': None}}, 'death': {'total': 50991, 'confirmed': None, 'probable': None}}}, {'date': '2021-02-24', 'state': 'CA', 'meta': {'data_quality_grade': 'B', 'updated': '2021-02-24T07:59:00Z', 'tests': {'total_source': 'totalTestsViral'}}, 'cases': {'total': 3455361, 'confirmed': 3455361, 'probable': None}, 'tests': {'pcr': {'total': 47652172, 'pending': None, 'encounters': {'total': None}, 'specimens': {'total': 47652172, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': 3455361, 'negative': None}}, 'antibody': {'encounters': {'total': None, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': None, 'negative': None}}, 'antigen': {'encounters': {'total': None, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': None, 'negative': None}}}, 'outcomes': {'recovered': None, 'hospitalized': {'total': None, 'currently': 6764, 'in_icu': {'total': None, 'currently': 1842}, 'on_ventilator': {'total': None, 'currently': None}}, 'death': {'total': 49877, 'confirmed': None, 'probable': None}}}, {'date': '2021-02-23', 'state': 'CA', 'meta': {'data_quality_grade': 'B', 'updated': '2021-02-23T07:59:00Z', 'tests': {'total_source': 'totalTestsViral'}}, 'cases': {'total': 3450058, 'confirmed': 3450058, 'probable': None}, 'tests': {'pcr': {'total': 47513367, 'pending': None, 'encounters': {'total': None}, 'specimens': {'total': 47513367, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': 3450058, 'negative': None}}, 'antibody': {'encounters': {'total': None, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': None, 'negative': None}}, 'antigen': {'encounters': {'total': None, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': None, 'negative': None}}}, 'outcomes': {'recovered': None, 'hospitalized': {'total': None, 'currently': 6908, 'in_icu': {'total': None, 'currently': 1898}, 'on_ventilator': {'total': None, 'currently': None}}, 'death': {'total': 49563, 'confirmed': None, 'probable': None}}}, {'date': '2021-02-22', 'state': 'CA', 'meta': {'data_quality_grade': 'B', 'updated': '2021-02-22T07:59:00Z', 'tests': {'total_source': 'totalTestsViral'}}, 'cases': {'total': 3446611, 'confirmed': 3446611, 'probable': None}, 'tests': {'pcr': {'total': 47320802, 'pending': None, 'encounters': {'total': None}, 'specimens': {'total': 47320802, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': 3446611, 'negative': None}}, 'antibody': {'encounters': {'total': None, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': None, 'negative': None}}, 'antigen': {'encounters': {'total': None, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': None, 'negative': None}}}, 'outcomes': {'recovered': None, 'hospitalized': {'total': None, 'currently': 7165, 'in_icu': {'total': None, 'currently': 2010}, 'on_ventilator': {'total': None, 'currently': None}}, 'death': {'total': 49338, 'confirmed': None, 'probable': None}}}, {'date': '2021-02-21', 'state': 'CA', 'meta': {'data_quality_grade': 'B', 'updated': '2021-02-21T07:59:00Z', 'tests': {'total_source': 'totalTestsViral'}}, 'cases': {'total': 3441946, 'confirmed': 3441946, 'probable': None}, 'tests': {'pcr': {'total': 47043348, 'pending': None, 'encounters': {'total': None}, 'specimens': {'total': 47043348, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': 3441946, 'negative': None}}, 'antibody': {'encounters': {'total': None, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': None, 'negative': None}}, 'antigen': {'encounters': {'total': None, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': None, 'negative': None}}}, 'outcomes': {'recovered': None, 'hospitalized': {'total': None, 'currently': 7313, 'in_icu': {'total': None, 'currently': 2073}, 'on_ventilator': {'total': None, 'currently': None}}, 'death': {'total': 49105, 'confirmed': None, 'probable': None}}}, {'date': '2021-02-20', 'state': 'CA', 'meta': {'data_quality_grade': 'B', 'updated': '2021-02-20T07:59:00Z', 'tests': {'total_source': 'totalTestsViral'}}, 'cases': {'total': 3435186, 'confirmed': 3435186, 'probable': None}, 'tests': {'pcr': {'total': 46813876, 'pending': None, 'encounters': {'total': None}, 'specimens': {'total': 46813876, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': 3435186, 'negative': None}}, 'antibody': {'encounters': {'total': None, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': None, 'negative': None}}, 'antigen': {'encounters': {'total': None, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': None, 'negative': None}}}, 'outcomes': {'recovered': None, 'hospitalized': {'total': None, 'currently': 7747, 'in_icu': {'total': None, 'currently': 2168}, 'on_ventilator': {'total': None, 'currently': None}}, 'death': {'total': 48825, 'confirmed': None, 'probable': None}}}, {'date': '2021-02-19', 'state': 'CA', 'meta': {'data_quality_grade': 'B', 'updated': '2021-02-19T07:59:00Z', 'tests': {'total_source': 'totalTestsViral'}}, 'cases': {'total': 3428518, 'confirmed': 3428518, 'probable': None}, 'tests': {'pcr': {'total': 46621654, 'pending': None, 'encounters': {'total': None}, 'specimens': {'total': 46621654, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': 3428518, 'negative': None}}, 'antibody': {'encounters': {'total': None, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': None, 'negative': None}}, 'antigen': {'encounters': {'total': None, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': None, 'negative': None}}}, 'outcomes': {'recovered': None, 'hospitalized': {'total': None, 'currently': 8156, 'in_icu': {'total': None, 'currently': 2291}, 'on_ventilator': {'total': None, 'currently': None}}, 'death': {'total': 48344, 'confirmed': None, 'probable': None}}}, {'date': '2021-02-18', 'state': 'CA', 'meta': {'data_quality_grade': 'B', 'updated': '2021-02-18T07:59:00Z', 'tests': {'total_source': 'totalTestsViral'}}, 'cases': {'total': 3421720, 'confirmed': 3421720, 'probable': None}, 'tests': {'pcr': {'total': 46504255, 'pending': None, 'encounters': {'total': None}, 'specimens': {'total': 46504255, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': 3421720, 'negative': None}}, 'antibody': {'encounters': {'total': None, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': None, 'negative': None}}, 'antigen': {'encounters': {'total': None, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': None, 'negative': None}}}, 'outcomes': {'recovered': None, 'hospitalized': {'total': None, 'currently': 8566, 'in_icu': {'total': None, 'currently': 2427}, 'on_ventilator': {'total': None, 'currently': None}}, 'death': {'total': 47924, 'confirmed': None, 'probable': None}}}, {'date': '2021-02-17', 'state': 'CA', 'meta': {'data_quality_grade': 'B', 'updated': '2021-02-17T07:59:00Z', 'tests': {'total_source': 'totalTestsViral'}}, 'cases': {'total': 3416147, 'confirmed': 3416147, 'probable': None}, 'tests': {'pcr': {'total': 46384932, 'pending': None, 'encounters': {'total': None}, 'specimens': {'total': 46384932, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': 3416147, 'negative': None}}, 'antibody': {'encounters': {'total': None, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': None, 'negative': None}}, 'antigen': {'encounters': {'total': None, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': None, 'negative': None}}}, 'outcomes': {'recovered': None, 'hospitalized': {'total': None, 'currently': 8855, 'in_icu': {'total': None, 'currently': 2533}, 'on_ventilator': {'total': None, 'currently': None}}, 'death': {'total': 47507, 'confirmed': None, 'probable': None}}}, {'date': '2021-02-16', 'state': 'CA', 'meta': {'data_quality_grade': 'B', 'updated': '2021-02-16T07:59:00Z', 'tests': {'total_source': 'totalTestsViral'}}, 'cases': {'total': 3412057, 'confirmed': 3412057, 'probable': None}, 'tests': {'pcr': {'total': 46227725, 'pending': None, 'encounters': {'total': None}, 'specimens': {'total': 46227725, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': 3412057, 'negative': None}}, 'antibody': {'encounters': {'total': None, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': None, 'negative': None}}, 'antigen': {'encounters': {'total': None, 'positive': None, 'negative': None}, 'people': {'total': None, 'positive': None, 'negative': None}}}, 'outcomes': {'recovered': None, 'hospitalized': {'total': None, 'currently': 9075, 'in_icu': {'total': None, 'currently': 2604}, 'on_ventilator': {'total': None, 'currently': None}}, 'death': {'total': 47107, 'confirmed': None, 'probable': None}}}, {'date': '2021-02-15', 'state': 'CA', 'meta': {'data_quality_grade': 'B', 'updated': '2021-02-15T07:59:00Z', 'tests': {'total_source': 'totalTestsViral'}}, 'cases': {'total': 3406365, 'confirmed': 3406365, 'prob

In [29]:
# converting json repsonses into dataframe using json_normalize method
df = pandas.json_normalize(responseData, 'data')
print(df)

           date state meta.data_quality_grade          meta.updated  \
0    2021-03-07    CA                       B  2021-03-07T07:59:00Z
1    2021-03-06    CA                       B  2021-03-06T07:59:00Z
2    2021-03-05    CA                       B  2021-03-05T07:59:00Z
3    2021-03-04    CA                       B  2021-03-04T07:59:00Z
4    2021-03-03    CA                       B  2021-03-03T07:59:00Z
..          ...   ...                     ...                   ...
364  2020-03-08    CA                    None                  None
365  2020-03-07    CA                    None                  None
366  2020-03-06    CA                    None                  None
367  2020-03-05    CA                    None                  None
368  2020-03-04    CA                    None                  None

    meta.tests.total_source  cases.total  cases.confirmed cases.probable  \
0           totalTestsViral      3501394          3501394           None
1           totalTestsViral      3497578          3497578           None
2           totalTestsViral      3493126          3493126           None
3           totalTestsViral      3488467          3488467           None
4           totalTestsViral      3484963          3484963           None
..                      ...          ...              ...            ...
364         totalTestsViral           88               88           None
365         totalTestsViral           69               69           None
366         totalTestsViral           60               60           None
367         totalTestsViral           53               53           None
368         totalTestsViral           53               53           None

     tests.pcr.total  tests.pcr.pending  ... outcomes.recovered  \
0           49646014                NaN  ...               None
1           49512828                NaN  ...               None
2           49294503                NaN  ...               None
3           49147685                NaN  ...               None
4           49028048                NaN  ...               None
..               ...                ...  ...                ...
364              550                NaN  ...               None
365              531                NaN  ...               None
366              522                NaN  ...               None
367              515                NaN  ...               None
368              515                NaN  ...               None

     outcomes.hospitalized.total outcomes.hospitalized.currently  \
0                           None                          4291.0
1                           None                          4513.0
2                           None                          4714.0
3                           None                          4967.0
4                           None                          5110.0
..                           ...                             ...
364                         None                             NaN
365                         None                             NaN
366                         None                             NaN
367                         None                             NaN
368                         None                             NaN

    outcomes.hospitalized.in_icu.total outcomes.hospitalized.in_icu.currently  \
0                                 None                                 1159.0
1                                 None                                 1221.0
2                                 None                                 1236.0
3                                 None                                 1327.0
4                                 None                                 1403.0
..                                 ...                                    ...
364                               None                                    NaN
365                               None                                    NaN
366                               None                                    NaN
367                               None                                    NaN
368                               None                                    NaN

     outcomes.hospitalized.on_ventilator.total  \
0                                         None
1                                         None
2                                         None
3                                         None
4                                         None
..                                         ...
364                                       None
365                                       None
366                                       None
367                                       None
368                                       None

     outcomes.hospitalized.on_ventilator.currently outcomes.death.total  \
0                                             None              54124.0
1                                             None              53866.0
2                                             None              53448.0
3                                             None              53048.0
4                                             None              52775.0
..                                             ...                  ...
364                                           None                  NaN
365                                           None                  NaN
366                                           None                  NaN
367                                           None                  NaN
368                                           None                  NaN

    outcomes.death.confirmed outcomes.death.probable
0                       None                    None
1                       None                    None
2                       None                    None
3                       None                    None
4                       None                    None
..                       ...                     ...
364                     None                    None
365                     None                    None
366                     None                    None
367                     None                    None
368                     None                    None

[369 rows x 39 columns]

In [36]:
# viewing first 10 rows of the created dataframe
df.head(10)

,date,state,meta.data_quality_grade,meta.updated,meta.tests.total_source,cases.total,cases.confirmed,cases.probable,tests.pcr.total,tests.pcr.pending,...,outcomes.recovered,outcomes.hospitalized.total,outcomes.hospitalized.currently,outcomes.hospitalized.in_icu.total,outcomes.hospitalized.in_icu.currently,outcomes.hospitalized.on_ventilator.total,outcomes.hospitalized.on_ventilator.currently,outcomes.death.total,outcomes.death.confirmed,outcomes.death.probable
0,2021-03-07,CA,B,2021-03-07T07:59:00Z,totalTestsViral,3501394,3501394,None,49646014,NaN,...,None,None,4291.0,None,1159.0,None,None,54124.0,None,None
1,2021-03-06,CA,B,2021-03-06T07:59:00Z,totalTestsViral,3497578,3497578,None,49512828,NaN,...,None,None,4513.0,None,1221.0,None,None,53866.0,None,None
2,2021-03-05,CA,B,2021-03-05T07:59:00Z,totalTestsViral,3493126,3493126,None,49294503,NaN,...,None,None,4714.0,None,1236.0,None,None,53448.0,None,None
3,2021-03-04,CA,B,2021-03-04T07:59:00Z,totalTestsViral,3488467,3488467,None,49147685,NaN,...,None,None,4967.0,None,1327.0,None,None,53048.0,None,None
4,2021-03-03,CA,B,2021-03-03T07:59:00Z,totalTestsViral,3484963,3484963,None,49028048,NaN,...,None,None,5110.0,None,1403.0,None,None,52775.0,None,None
5,2021-03-02,CA,B,2021-03-02T07:59:00Z,totalTestsViral,3481611,3481611,None,48897190,NaN,...,None,None,5302.0,None,1452.0,None,None,52497.0,None,None
6,2021-03-01,CA,B,2021-03-01T07:59:00Z,totalTestsViral,3479078,3479078,None,48712676,NaN,...,None,None,5409.0,None,1518.0,None,None,52194.0,None,None
7,2021-02-28,CA,B,2021-02-28T07:59:00Z,totalTestsViral,3475562,3475562,None,48469106,NaN,...,None,None,5674.0,None,1585.0,None,None,51979.0,None,None
8,2021-02-27,CA,B,2021-02-27T07:59:00Z,totalTestsViral,3470877,3470877,None,48219490,NaN,...,None,None,5897.0,None,1651.0,None,None,51821.0,None,None
9,2021-02-26,CA,B,2021-02-26T07:59:00Z,totalTestsViral,3465726,3465726,None,47995576,NaN,...,None,None,6152.0,None,1725.0,None,None,51382.0,None,None

In [35]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 369 entries, 0 to 368
Data columns (total 39 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   date                                           369 non-null    object
 1   state                                          369 non-null    object
 2   meta.data_quality_grade                        350 non-null    object
 3   meta.updated                                   361 non-null    object
 4   meta.tests.total_source                        369 non-null    object
 5   cases.total                                    369 non-null    int64
 6   cases.confirmed                                369 non-null    int64
 7   cases.probable                                 0 non-null      object
 8   tests.pcr.total                                369 non-null    int64
 9   tests.pcr.pending                              28 non-null     float64
 10  tests.pcr.encounters.total                     0 non-null      object
 11  tests.pcr.specimens.total                      369 non-null    int64
 12  tests.pcr.specimens.positive                   0 non-null      object
 13  tests.pcr.specimens.negative                   0 non-null      object
 14  tests.pcr.people.total                         0 non-null      object
 15  tests.pcr.people.positive                      369 non-null    int64
 16  tests.pcr.people.negative                      49 non-null     float64
 17  tests.antibody.encounters.total                0 non-null      object
 18  tests.antibody.encounters.positive             0 non-null      object
 19  tests.antibody.encounters.negative             0 non-null      object
 20  tests.antibody.people.total                    0 non-null      object
 21  tests.antibody.people.positive                 0 non-null      object
 22  tests.antibody.people.negative                 0 non-null      object
 23  tests.antigen.encounters.total                 0 non-null      object
 24  tests.antigen.encounters.positive              0 non-null      object
 25  tests.antigen.encounters.negative              0 non-null      object
 26  tests.antigen.people.total                     0 non-null      object
 27  tests.antigen.people.positive                  0 non-null      object
 28  tests.antigen.people.negative                  0 non-null      object
 29  outcomes.recovered                             0 non-null      object
 30  outcomes.hospitalized.total                    0 non-null      object
 31  outcomes.hospitalized.currently                346 non-null    float64
 32  outcomes.hospitalized.in_icu.total             0 non-null      object
 33  outcomes.hospitalized.in_icu.currently         346 non-null    float64
 34  outcomes.hospitalized.on_ventilator.total      0 non-null      object
 35  outcomes.hospitalized.on_ventilator.currently  0 non-null      object
 36  outcomes.death.total                           361 non-null    float64
 37  outcomes.death.confirmed                       0 non-null      object
 38  outcomes.death.probable                        0 non-null      object
dtypes: float64(5), int64(5), object(29)
memory usage: 112.6+ KB

,cases.total,cases.confirmed,tests.pcr.total,tests.pcr.pending,tests.pcr.specimens.total,tests.pcr.people.positive,tests.pcr.people.negative,outcomes.hospitalized.currently,outcomes.hospitalized.in_icu.currently,outcomes.death.total
count,3.690000e+02,3.690000e+02,3.690000e+02,28.000000,3.690000e+02,3.690000e+02,49.000000,346.000000,346.000000,361.000000
mean,1.027373e+06,1.027373e+06,1.580863e+07,29110.714286,1.580863e+07,1.027373e+06,70570.040816,7669.398844,1932.638728,15881.132964
std,1.110252e+06,1.110252e+06,1.513823e+07,22975.193374,1.513823e+07,1.110252e+06,87413.606228,5611.082960,1176.489960,14011.898720
min,5.300000e+01,5.300000e+01,5.150000e+02,7200.000000,5.150000e+02,5.300000e+01,462.000000,746.000000,200.000000,4.000000
25%,1.198070e+05,1.198070e+05,2.182671e+06,13200.000000,2.182671e+06,1.198070e+05,7981.000000,4264.750000,1202.250000,4776.000000
50%,7.222830e+05,7.222830e+05,1.179697e+07,14100.000000,1.179697e+07,7.222830e+05,20549.000000,5163.000000,1488.500000,13758.000000
75%,1.311625e+06,1.311625e+06,2.490198e+07,57400.000000,2.490198e+07,1.311625e+06,145191.000000,8575.000000,2206.250000,19935.000000
max,3.501394e+06,3.501394e+06,4.964601e+07,64400.000000,4.964601e+07,3.501394e+06,266839.000000,22851.000000,4971.000000,54124.000000

In [34]:
# Define your database connection details
# create a DB name COVID19 in postgresql and then run this code.
DATABASE_URL = "postgresql+psycopg2://username:password@server:port/COVID19_new"

# Create an SQLAlchemy engine
engine = sqlalchemy.create_engine(DATABASE_URL)
with engine.begin() as connection:
    df.to_sql(name='COVID_19_CA', con=connection, index=False, if_exists='append')